#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged && git diff --cached --diff-filter=d --name-only -- '*.spec.ts' | xargs -I {} ng test --include={} --browsers=ChromeHeadless --watch=false
